package com.example.aniru.popmovies1;

/**
 * Created by aniru on 7/15/2017.
 */

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

// Autogenerated class to map JSON to POJO
class Movies {
    @SerializedName("page")
    @Expose
    private Integer page;
    @SerializedName("total_results")
    @Expose
    private Integer totalResults;
    @SerializedName("total_pages")
    @Expose
    private Integer totalPages;
    @SerializedName("results")
    @Expose
    // private List<MovieDBAPI_ResponseResults> results = null;
    private ArrayList<MovieDBAPI_ResponseResults> results = null;

    public ArrayList<MovieDBAPI_ResponseResults> getResults() {
        return results;
    }

    public void setResults(ArrayList<MovieDBAPI_ResponseResults> results) {
        this.results = results;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getTotalResults() {
        return totalResults;
    }

    public void setTotalResults(Integer totalResults) {
        this.totalResults = totalResults;
    }

    public Integer getTotalPages() {
        return totalPages;
    }

    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

}


